title: Déjà Entendu
description: A Mac and iOS app for capturing spoken language and transcribing to a user's native language for practice, entirely on-device.
theme: jekyll-theme-cayman
show_downloads: false
